version: '3.8'

services:
  main_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    
    environment:
      - ENVIRONMENT=development
    networks:
      - default
    #command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
  db_api:
    #image: devfullstackavancadodbapi:latest
    build:
      context: ../devfullstackavancadodbapi
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - default

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "127.0.0.1"