version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    depends_on:
      - devfullstackavancadodbapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
  devfullstackavancadodbapi:
    #image: devfullstackavancadodbapi:latest
    build: .
    ports:
      - "5000:5000"